# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Home Automation UI App

on:
  push:
    paths:
      - client/**

defaults:
  run:
    working-directory: ./client
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./client
      
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: us-east-1

    # - name: Deploy S3 Bucket Using CloudFormation
    #   uses: aws-actions/aws-cloudformation-github-deploy@v1
    #   with:
    #     name: client
    #     template: ./automation/ui/cloudformation/s3_static_website.yaml
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
    #     aws-region: us-east-1
    #     no-fail-on-empty-changeset: "1"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Yarn Install
      run: |
        yarn install

    - name: Build
      run: yarn run build

    # - name: Deploy to S3
    #   run: aws s3 sync ./build s3://smarthomeautomation.com
